[package]
name = "package"
version = "0.2.0"
description = "Packages the scie-pants binary."
authors = [
    "John Sirois <john.sirois@gmail.com>",
]
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.0", features = ["derive"] }
proc-exit = "2.0"
sha2 = "0.10"
